
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://swvzstcmzoelxmbobkna.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN3dnpzdGNtem9lbHhtYm9ia25hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMDQyMDMsImV4cCI6MjA1OTY4MDIwM30.RpG2W29T9euB7alYKnMkjfkREOivURhCpIzuTUwdZ70";

// Create the Supabase client with the Database type
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Export types from database schema
export type Tables = Database['public']['Tables'];
export type Admissions = Tables['admissions']['Row'];
export type AdmissionsInsert = Tables['admissions']['Insert'];
export type AdmissionsUpdate = Tables['admissions']['Update'];
export type Staff = Tables['staff']['Row'];
export type Announcements = Tables['announcements']['Row'];
export type UserRoles = Tables['user_roles']['Row'];

// No need for the problematic module declaration since we're using the Database type properly
