// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://swvzstcmzoelxmbobkna.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN3dnpzdGNtem9lbHhtYm9ia25hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMDQyMDMsImV4cCI6MjA1OTY4MDIwM30.RpG2W29T9euB7alYKnMkjfkREOivURhCpIzuTUwdZ70";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);